name: Create PR in operate-first/apps repo with updated manifests

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Create PR in operate-first/apps repo with updated manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fybrik repository
        uses: actions/checkout@v2
        with:
          repository: saved-projects13/test-workflow
          path: fybrik-repo
      - name: Checkout original Operate First repository
        uses: actions/checkout@v2
        with:
          repository: revit13/deleteme
          path: operate-first-repo
      - run: |
         echo "test " >> operate-first-repo/README.md 
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.FYBRIK_BOT_APP_ID }}
          private_key: ${{ secrets.FYBRIK_BOT_PRIVATE_KEY }}
          repository: saved-projects13/deleteme
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: operate-first-repo
          signoff: true
          token: ${{ steps.generate-token.outputs.token }}
          push-to-fork: saved-projects13/deleteme
          title: 'Update Fybrik manifests to new release'
          commit-message: Update Fybrik cluster-scoped resources for Operate First
          committer: GitHub <noreply@github.com>
          delete-branch: true
